services:
  mysql:
    image: mysql:8.0
    container_name: mysql-cassino-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: CassinoRoot123!
      MYSQL_DATABASE: ApiCassinoDb
      MYSQL_USER: cassinouser
      MYSQL_PASSWORD: CassinoPass123!
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: